'use client'

import { useEffect, useState } from 'react'
import { ArrowRight, BriefcaseBusiness, ChevronDown, ChevronUp, Handshake, Heart, Camera, Menu, Phone, Send, Sparkles, Trophy, Wrench, X } from 'lucide-react'

const projects = [
  { title: 'Área Educativa', color: 'red', icon: Sparkles, description: 'Acompañamos trayectorias educativas en cada etapa.', items: ['Apoyo escolar 6–12 años', 'Apoyo adolescentes', 'Alfabetización adultos'] },
  { title: 'Área Deportivo-recreativa', color: 'teal', icon: Trophy, description: 'El movimiento como encuentro, salud y comunidad.', items: ['Vóley y fútbol', 'Pilates M.A.T.', 'Circuito saludable'] },
  { title: 'Área Cultural', color: 'yellow', icon: Sparkles, description: 'Espacios para crear, expresarse y descubrir talentos.', items: ['Teclado, batería y canto', 'Danza, folklore y tejido', 'Teatro'] },
  { title: 'Formación y Capacitación', color: 'purple', icon: Wrench, description: 'Herramientas concretas para el trabajo y la autonomía.', items: ['Manipulación de alimentos', 'Maestro pizzero', 'Robótica, diseño 3D e informática'] },
  { title: 'Área Social', color: 'pink', icon: Heart, description: 'Redes de cuidado para acompañar a las familias.', items: ['Peluquería gratuita', 'Asistencia social', 'Derivaciones a comedores'] },
]
const timeline = [['Sept. 2017', 'Comienzan las actividades de apoyo escolar. Cerramos el año con 97 niños.'], ['Abril 2018', 'Inscripción de 120 niños con programa renovado.'], ['Hoy', 'Apoyo escolar, música, danza, arte, teatro, folklore, vóley, fútbol, Pilates M.A.T.'], ['Próximamente', 'Cursos de oficios, breakdance y danzas contemporáneas.']]
const help = [['red', 'Útiles escolares', 'Ayudanos a equipar a quienes vienen a apoyo escolar.'], ['yellow', 'Materiales para talleres', 'Insumos para los espacios culturales y deportivos.'], ['teal', 'Herramientas', 'Elementos para los cursos de capacitación en oficios.'], ['purple', 'Donación económica', 'Un aporte sostiene cada una de las áreas del Centro.']]
const events = [
  ['18 JUN', 'Entrega de certificados de AWS'],
  ['22 JUN', 'Entrega de alimentos'],
  ['06 JUL', 'Fiesta del día del niño'],
  ['20 JUL', 'Taller de robótica comunitaria'],
  ['03 AGO', 'Encuentro deportivo familiar'],
]
const carouselSlides = [
  { image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/clase-musica-oozavGIfUzwdCvu3Sfar0eCi3oKHZi.jpeg', alt: 'Niños y jóvenes participan de una clase de música', label: 'Comunidad en acción', title: 'Aprender, compartir y crecer juntos' },
  { image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-19%20at%209.39.11%20PM%20%281%29-hBBHq7hYfgBoRKKHcJBXzWODNyWMXK.jpeg', alt: 'Robots construidos para una actividad educativa', label: 'Formación y creatividad', title: 'Explorar, construir e imaginar' },
  { image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-09-19%20at%209.38.51%20PM%20%282%29-MQsB7FaRhjSkmsYGAcv9dODhGgYPCK.jpeg', alt: 'Niños participan de una actividad deportiva en un gimnasio', label: 'Deporte y encuentro', title: 'Jugar en equipo, crecer en comunidad' },
]
const eventDetails = events.map(([date, title], index) => ({ date, title, description: 'Un encuentro para compartir, aprender y celebrar lo que hacemos en comunidad.', images: [carouselSlides[index % carouselSlides.length], carouselSlides[(index + 1) % carouselSlides.length], carouselSlides[(index + 2) % carouselSlides.length]] }))

function Intro({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div> }

const projectDetails = {
  'Área Educativa': { detail: 'Acompañamos a niñas, niños, adolescentes y personas adultas con apoyo escolar, alfabetización y herramientas para sostener sus trayectorias educativas.', image: carouselSlides[0].image, alt: carouselSlides[0].alt },
  'Área Deportivo-recreativa': { detail: 'Creamos espacios de juego, movimiento y encuentro a través del vóley, fútbol, Pilates M.A.T. y circuitos saludables.', image: carouselSlides[2].image, alt: carouselSlides[2].alt },
  'Área Cultural': { detail: 'Promovemos la expresión y el descubrimiento de talentos con talleres de música, danza, folklore, tejido y teatro.', image: carouselSlides[0].image, alt: carouselSlides[0].alt },
  'Formación y Capacitación': { detail: 'Ofrecemos capacitaciones prácticas en oficios y tecnología para fortalecer la autonomía y ampliar oportunidades laborales.', image: carouselSlides[1].image, alt: carouselSlides[1].alt },
  'Área Social': { detail: 'Acompañamos a las familias con redes de cuidado, asistencia social, peluquería gratuita y derivaciones a comedores.', image: carouselSlides[2].image, alt: carouselSlides[2].alt },
} as const

type ProjectTitle = keyof typeof projectDetails

function Carousel() {
  const [active, setActive] = useState(0)
  const slide = carouselSlides[active]
  useEffect(() => {
    const timer = window.setInterval(() => setActive((current) => (current + 1) % carouselSlides.length), 5000)
    return () => window.clearInterval(timer)
  }, [])
  return <div className="hero-carousel" aria-label="Escenas de la comunidad del Centro Crecer"><img src={slide.image} alt={slide.alt} /><div className="hero-carousel-overlay" /><div className="hero-carousel-caption"><span>{slide.label}</span><strong>{slide.title}</strong></div><div className="carousel-dots" aria-label={`Diapositiva ${active + 1} de ${carouselSlides.length}`}>{carouselSlides.map((item, index) => <button key={item.image} className={index === active ? 'active' : ''} onClick={() => setActive(index)} aria-label={`Ver diapositiva ${index + 1}`} />)}</div></div>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [faq, setFaq] = useState<number | null>(0)
  const [selectedProject, setSelectedProject] = useState<ProjectTitle | null>(null)
  const [activeEvent, setActiveEvent] = useState(0)
  const [selectedEvent, setSelectedEvent] = useState<number | null>(null)
  const [expandedEventImage, setExpandedEventImage] = useState(0)
  const selectedProjectData = selectedProject ? projectDetails[selectedProject] : null
  const selectedEventData = selectedEvent !== null ? eventDetails[selectedEvent] : null

  useEffect(() => {
    if (!selectedProject && selectedEvent === null) return
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setSelectedProject(null)
        setSelectedEvent(null)
        setExpandedEventImage(0)
      }
    }
    document.addEventListener('keydown', closeOnEscape)
    document.body.style.overflow = 'hidden'
    return () => {
      document.removeEventListener('keydown', closeOnEscape)
      document.body.style.overflow = ''
    }
  }, [selectedProject, selectedEvent])
  return <>
    <a className="skip-link" href="#contenido">Ir al contenido</a>
    <header className="site-header"><a className="brand" href="#inicio" aria-label="Centro Crecer, inicio"><img className="brand-logo brand-logo-header" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo-horizontal-color-RK37Le6wkQ5LeqLofefdVjH6queWa5.png" alt="Centro Crecer" /></a><a className="social-link header-social" href="https://www.instagram.com/centrocrecer/" target="_blank" rel="noreferrer" aria-label="Instagram de Centro Crecer"><Camera /></a><nav className="desktop-nav" aria-label="Navegación principal"><a href="#institucional">Institucional</a><a href="#voluntariado">Voluntariado</a><a href="#proyectos">Proyectos</a><a href="#eventos">Eventos</a><a href="#ayudar">Cómo ayudar</a><a href="#alianzas">Alianzas sociales</a><a href="#contacto">Contacto</a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'}>{menuOpen ? <X /> : <Menu />}</button>{menuOpen && <nav className="mobile-nav" aria-label="Menú móvil"><a href="#institucional" onClick={() => setMenuOpen(false)}>Institucional</a><a href="#voluntariado" onClick={() => setMenuOpen(false)}>Voluntariado</a><a href="#proyectos" onClick={() => setMenuOpen(false)}>Proyectos</a><a href="#eventos" onClick={() => setMenuOpen(false)}>Eventos</a><a href="#alianzas" onClick={() => setMenuOpen(false)}>Alianzas sociales</a><a href="#contacto" onClick={() => setMenuOpen(false)}>Contacto</a></nav>}</header>
    <main id="contenido">
      <section className="hero" id="inicio"><div className="container hero-grid"><div className="hero-copy"><span className="hero-badge">Desde 2017 · Buenos Aires</span><h1>Acompañamos a crecer a cada persona de nuestro barrio</h1><p>Apoyo escolar, deporte, cultura y formación para vecinos de San Telmo, Constitución, Barracas, Monserrat y Balvanera.</p><div className="hero-actions"><a className="button button-purple" href="#voluntariado">Convertite en voluntario <ArrowRight data-icon="inline-end" /></a></div></div><Carousel /></div><div className="container stats"><span><i className="dot red" />9 años · Extendiendo nuestras manos</span><span><i className="dot yellow" />17+ Proyectos</span><span><i className="dot teal" />92+ Voluntarios</span></div></section>
      <section className="section" id="institucional"><div className="container"><Intro eyebrow="Institucional" title="Quiénes somos">Un espacio de encuentro, acompañamiento y crecimiento integral.</Intro><div className="mission-grid"><article className="border-card red-border"><span className="card-label">Visión</span><h3>Una existencia más digna y humana</h3><p>El Centro CRECER se fundamenta en la visión de la Iglesia del Centro, buscando afectar integralmente las vidas de las personas y de la comunidad.</p></article><article className="border-card yellow-border"><span className="card-label">Misión</span><h3>Restaurar, promover, acompañar</h3><p>Nuestro llamado aquí y ahora es poner en funcionamiento mecanismos de restauración que respondan a las necesidades integrales de la comunidad.</p></article></div><div className="history-grid"><div><span className="eyebrow">Nuestra historia</span><p>Desde septiembre de 2017 brindamos contención y apoyo escolar para afianzar conocimientos, evitar el abandono escolar y acompañar también a las familias.</p></div><div className="timeline">{timeline.map(([date, text]) => <div className="timeline-item" key={date}><span className="timeline-dot" /><span className="timeline-date">{date}</span><p>{text}</p></div>)}</div></div></div></section>
      <section className="section soft-section" id="proyectos"><div className="container"><Intro eyebrow="Proyectos" title="Cinco áreas para acompañar el crecimiento" /> <div className="projects-grid">{projects.map(({ title, color, icon: Icon, description, items }) => <button className={`project-card top-${color}`} key={title} type="button" onClick={() => setSelectedProject(title as ProjectTitle)}><Icon className="project-icon" /><h3>{title}</h3><p>{description}</p><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><span className="project-card-link">Conocé esta área <ArrowRight data-icon="inline-end" /></span></button>)}</div></div></section>
      <section className="section" id="eventos" aria-labelledby="eventos-titulo"><div className="container"><Intro eyebrow="Eventos" title="Lo que vamos viviendo juntos" /><div className="events-carousel"><button className="carousel-arrow" type="button" onClick={() => setActiveEvent((activeEvent - 1 + events.length) % events.length)} aria-label="Evento anterior">‹</button>{[0, 1].map((offset) => { const [date, title] = events[(activeEvent + offset) % events.length]; return <article className="event-card" key={`${title}-${activeEvent}`} role="button" tabIndex={0} onClick={() => { setSelectedEvent(events.findIndex((event) => event[1] === title)); setExpandedEventImage(0) }} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setSelectedEvent(events.findIndex((item) => item[1] === title)); setExpandedEventImage(0) } }}><div className="event-placeholder"><Sparkles /></div><div><span className="event-date">● {date} · 2026</span><h3>{title}</h3><p>Un encuentro para compartir, aprender y celebrar lo que hacemos.</p><span className="event-card-link">Ver más <ArrowRight data-icon="inline-end" /></span></div></article> })}<button className="carousel-arrow" type="button" onClick={() => setActiveEvent((activeEvent + 1) % events.length)} aria-label="Siguiente evento">›</button></div></div></section>
      <section className="section soft-section" id="voluntariado"><div className="container volunteer-grid"><div><Intro eyebrow="Voluntariado" title="Tu servicio ayudará a transformar realidades" /><p>Hay muchas maneras de poner tus dones al servicio de otros. Encontrá tu lugar en una comunidad que está creciendo.</p><ol className="steps">{['Te hacemos una entrevista para conocerte.', 'Completás el formulario de intención.', 'Recibís la capacitación.', 'Pasás a formar parte del equipo.'].map((step, i) => <li key={step}><span>{i + 1}</span>{step}</li>)}</ol><div className="button-row"><a className="button button-purple" href="#contacto">Convertite en voluntario</a></div></div><div className="image-grid"><div /><div /><div /><div /></div></div></section>
      <section className="section" id="alianzas"><div className="container"><Intro eyebrow="Alianzas sociales" title="Crecemos mejor en red" /><div className="alliance-grid"><article className="border-card"><Handshake className="project-icon" /><h3>Convenios</h3><p>Construimos acuerdos con organizaciones y espacios que comparten nuestra mirada para multiplicar el impacto.</p></article><article className="border-card"><BriefcaseBusiness className="project-icon" /><h3>Responsabilidad Social Empresaria</h3><p>Conectamos empresas con proyectos concretos para que sus recursos lleguen donde más se necesitan.</p></article></div></div></section>
      <section className="section soft-section" id="ayudar"><div className="container"><Intro eyebrow="Cómo ayudar" title="Tu contribución es enorme para quienes lo necesitan" /><div className="help-grid">{help.map(([color, title, text], i) => <article className={`help-card ${color}-border`} key={title}><span className="card-label">0{i + 1}</span><h3>{title}</h3><p>{text}</p>{i === 3 && <details><summary>Ver datos bancarios</summary><p>Banco Nación · CBU disponible al escribirnos.</p></details>}</article>)}</div></div></section>
      <section className="contact-band"><div className="container contact-band-inner"><h2>¿Querés comunicarte con nosotros?</h2><div><a href="tel:43043346"><Phone data-icon="inline-start" /> 4304-3346</a><a href="https://wa.me/5491164301273">WhatsApp <ArrowRight data-icon="inline-end" /></a></div></div></section>
      <section className="section" id="contacto"><div className="container contact-grid"><div><Intro eyebrow="Contacto" title="Escribinos" /><form onSubmit={(e) => e.preventDefault()}><label>Motivo<select defaultValue=""><option value="" disabled>Elegí una opción</option><option>Quiero ser voluntario/a</option><option>Quiero ayudar</option><option>Tengo una consulta</option></select></label><label>Nombre y apellido<input required /></label><label>Mail<input required type="email" /></label><label>Teléfono (opcional)<input /></label><label>Mensaje<textarea rows={5} required /></label><button className="button button-purple" type="submit">Enviar mensaje <Send data-icon="inline-end" /></button></form></div><div className="faq"><span className="eyebrow">Preguntas frecuentes</span>{['¿Cómo me sumo como voluntario?', '¿Las actividades son gratuitas?', '¿Dónde queda el Centro?', '¿Cómo puedo colaborar sin ser voluntario?'].map((q, i) => <div className="faq-item" key={q}><button onClick={() => setFaq(faq === i ? null : i)}>{q}{faq === i ? <ChevronUp /> : <ChevronDown />}</button>{faq === i && <p>{i === 0 ? 'Escribinos a través del formulario y te vamos a contactar para conocerte.' : 'Sí. Todas nuestras actividades son gratuitas y abiertas a la comunidad.'}</p>}</div>)}</div></div></section>
    </main>
    {selectedEventData && <div className="project-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setSelectedEvent(null)}><section className="project-modal event-modal" role="dialog" aria-modal="true" aria-labelledby="event-modal-title"><button className="modal-close" type="button" onClick={() => setSelectedEvent(null)} aria-label="Cerrar detalle del evento"><X /></button><img className="event-modal-main-image" src={selectedEventData.images[expandedEventImage].image} alt={selectedEventData.images[expandedEventImage].alt} /><div className="event-modal-content"><span className="eyebrow">Evento · {selectedEventData.date} · 2026</span><h2 id="event-modal-title">{selectedEventData.title}</h2><p>{selectedEventData.description}</p><div className="event-gallery" aria-label="Galería de imágenes del evento">{selectedEventData.images.map((image, index) => <button type="button" className={index === expandedEventImage ? 'active' : ''} key={image.image} onClick={() => setExpandedEventImage(index)}><img src={image.image} alt={image.alt} /></button>)}</div></div></section></div>}
    {selectedProject && selectedProjectData && <div className="project-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setSelectedProject(null)}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-modal-title"><button className="modal-close" type="button" onClick={() => setSelectedProject(null)} aria-label="Cerrar detalle del área"><X /></button><img src={selectedProjectData.image} alt={selectedProjectData.alt} /><div className="project-modal-content"><span className="eyebrow">Área de crecimiento</span><h2 id="project-modal-title">{selectedProject}</h2><p>{selectedProjectData.detail}</p><div className="project-modal-actions"><a className="button button-purple" href="#contacto" onClick={() => setSelectedProject(null)}>Ir al formulario de inscripción <ArrowRight data-icon="inline-end" /></a><button className="modal-secondary-action" type="button" onClick={() => setSelectedProject(null)}>Volver a áreas</button></div></div></section></div>}
    <footer><div className="container footer-grid"><div className="footer-brand-column"><a className="brand footer-brand" href="#inicio"><img className="brand-logo" src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo-horizontal-blanco-transparente-I3u6vWprxKC8C8vWuTRO2ZPgof2wHa.png" alt="Centro Crecer" /></a><a className="social-link footer-social" href="https://www.instagram.com/centrocrecer/" target="_blank" rel="noreferrer" aria-label="Instagram de Centro Crecer"><Camera /></a></div><div className="footer-links"><div><strong>Institucional</strong><a href="#institucional">Quiénes somos</a><a href="#institucional">Historia</a></div><div><strong>Participá</strong><a href="#voluntariado">Voluntariado</a><a href="#alianzas">Alianzas</a></div><div><strong>Proyectos</strong><a href="#proyectos">Áreas de trabajo</a><a href="#ayudar">Cómo ayudar</a></div><div><strong>Contacto</strong><a href="https://maps.google.com/?q=Buenos+Aires,+Argentina" target="_blank" rel="noreferrer">Buenos Aires, Argentina</a><a href="tel:43043346">4304-3346</a><a href="mailto:info@centrocrecer.org.ar">info@centrocrecer.org.ar</a></div><div><strong>Información</strong><a href="#politicas">Políticas de privacidad</a><a href="#cookies">Política de cookies</a></div></div></div><div className="container footer-bottom"><span>© 2026 Centro Crecer</span><span>Buenos Aires, Argentina</span></div></footer>
  </>
}
